config/routes.rb
Rails.application.routes.draw do

  resources :posts
  root 'posts#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  scope :latest, -> (limit = 5) { order(created_at: :desc).limit(limit) }
end

app/controllers/application_controller.rb
# -*- encoding: UTF-8 -*-
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
# -*- encoding: UTF-8 -*-
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to "/posts/#{@post.id}"
  end

  def show
    # @post = Post.find(params[:id])
  end

  def index
    @posts = Post.latest
  end

  def edit
    # @post = Post.find(params[:id])
  end

  def update
    # @post = Post.find(params[:id])
    @post.update_attributes(post_params)
    redirect_to "/posts/#{@post.id}"
  end

  def destroy
    # @post = Post.find(params[:id])
    @post.destroy
    redirect_to "/"
  end

  private

  def post_params
    params.require(:post).permit(
      :title,
      :body,
      :category,
      :category_id
      )
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlogReview4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/posts">ブログ</a>
    </div>



  <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/posts/new">投稿する</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>





<div class="container">
  <div class="row">
<%= yield %>
  </div>
</div>

</body>
</html>

app/views/posts/edit.html.erb
<div class="col-md-12">

<h1>記事を編集する</h1>

<%= form_for @post, url: { action: :update} do |f| %>

<div class="form-group">
  <%= f.label "タイトル" %>
  <%= f.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label "カテゴリ" %>
  <%= f.collection_select(:category_id, Category.all,:id,:title,class: "form-control") %>
</div>

<div class="form-group">
  <%= f.label "本文" %>
  <%= f.text_area :body, class: "form-control" %>
</div>

  <%= f.submit '編集する', class: "btn btn-primary" %>
  <% end %>


</div>

app/views/posts/index.html.erb
<div class="col-md-8">

<h1>記事一覧</h1>


</div>

<div class="col-md-4">
  <div class="thumbnail">
    <% author = Author.first %>
    <img src="https://scontent.xx.fbcdn.net/hphotos-xtp1/v/t1.0-9/r90/11223697_671152656352037_5566942386190532809_n.jpg?oh=012005fcf86c70a8cddd27763a99603f&oe=5643562F" alt="著者画像">
    <div class="caption">
      <h3>著者の名前</h3>
      <p>著者の説明です</p>
    </div>
  </div>



  <div class="list-group">
  <% @posts.each do |post| %>
  <br>
  <h4><%= link_to post.title, post_path(post) %></h4>
  <% end %>
  </div>




</div>

app/views/posts/new.html.erb
<div class="col-md-12">

<h1>新規記事投稿</h1>

<%= form_for @post do |f| %>
<div class="form-group">
  <%= f.label "タイトル" %>
  <%= f.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label "カテゴリ" %>
  <%= f.collection_select(:category_id, Category.all,:id,:title,class: "form-control") %>
</div>

<div class="form-group">
  <%= f.label "本文" %>
  <%= f.text_area :body, class: "form-control" %>
</div>

  <%= f.submit '登録する',class: "btn btn-primary" %>
  <% end %>



</div>

app/views/posts/show.html.erb
<div class="col-md-12">

<h1><%= @post.title %></h1>
  <p>カテゴリ:
  <%= Category.find(@post.category_id).title %></p>

  <p>投稿日:
  <%= @post.created_at %>
  </p>

  <hr>

  <p><%= simple_format(@post.body) %></p>

  <hr>

<%= link_to '編集する',edit_post_path, class: "btn btn-default" %>
<%= link_to '削除する',post_path, method: :delete,data: {confirm: '本当に削除しますか？'}, class: "btn btn-danger" %>
<%= link_to '戻る',root_path, class: "btn btn-info" %>

</div>